CREATE TABLE REGISTER (
	DOCNO VARCHAR(100),
	TITLE VARCHAR(500),
	ORGANIZATION VARCHAR(500),
	REVISION VARCHAR(4),
	REVISION_DATE VARCHAR(20),
	DOC_VERSION NUMBER,
	REGISTERED_BY VARCHAR(200),
	REGISTERED VARCHAR(20),
	INT_CD VARCHAR(200),
	DESCR VARCHAR(4000),
	DISCIPLINE VARCHAR(200),
	REVIEW_STATUS VARCHAR(200),
	DOC_STATUS VARCHAR(200),
	DOC_TYPE VARCHAR(1000),
	ATTRIB1 VARCHAR(200),
	ATTRIB2 VARCHAR(200),
	ATTRIB3 VARCHAR(200),
	ATTRIB4 VARCHAR(200),
	DOC_CURRENT VARCHAR(1),
	INTERNAL_CODES VARCHAR2(200)
);

CREATE TABLE REVIEW_INFO ( 
	DOCNO TEXT,
	DOC_VERSION TEXT,
	REVIEW_DATE TEXT,
	REVIEW_STATUS TEXT,
	REVIEW_NOTE TEXT,
	REVIEWED_BY TEXT
);

CREATE TABLE CLSS ( 
	LEVEL TEXT,
	CODE TEXT,
	NAME TEXT
);