//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pmis.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://p-city.kspmis.com")]
        public string pmis_api_url {
            get {
                return ((string)(this["pmis_api_url"]));
            }
            set {
                this["pmis_api_url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PCITY_PMIS")]
        public string pmis_project_code {
            get {
                return ((string)(this["pmis_project_code"]));
            }
            set {
                this["pmis_project_code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pmis_auth_key {
            get {
                return ((string)(this["pmis_auth_key"]));
            }
            set {
                this["pmis_auth_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>일반</string>
  <string>건축</string>
  <string>구조</string>
  <string>토목</string>
  <string>조경</string>
  <string>기계</string>
  <string>전기</string>
  <string>통신</string>
  <string>소방</string>
  <string>Other</string>
  <string>계측</string>
  <string>M</string>
  <string>P</string>
  <string>F</string>
  <string>H</string>
  <string>R</string>
  <string>J</string>
  <string>E</string>
  <string>C</string>
  <string>A</string>
  <string>S</string>
  <string>Q</string>
  <string>X</string>
  <string>T</string>
  <string>V</string>
  <string>공통</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection register_discipline {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["register_discipline"]));
            }
            set {
                this["register_discipline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>정보용</string>
  <string>공사용</string>
  <string>승인용</string>
  <string>폐기</string>
  <string>완료</string>
  <string>임시</string>
  <string>승인</string>
  <string>정보</string>
  <string>검토</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection register_status {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["register_status"]));
            }
            set {
                this["register_status"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Drawing &gt; Start construction drawing/doc. &gt; 건축</string>\r\n  <string>D" +
            "rawing &gt; Start construction drawing/doc. &gt; 구조</string>\r\n  <string>Drawing " +
            "&gt; Start construction drawing/doc. &gt; 기계 &gt; MA(공통)</string>\r\n  <string>Dra" +
            "wing &gt; Start construction drawing/doc. &gt; 기계 &gt; MC(자동제어)</string>\r\n  <str" +
            "ing>Drawing &gt; Start construction drawing/doc. &gt; 기계 &gt; MD(공조덕트)</string>\r" +
            "\n  <string>Drawing &gt; Start construction drawing/doc. &gt; 기계 &gt; ME(냉매배관)</s" +
            "tring>\r\n  <string>Drawing &gt; Start construction drawing/doc. &gt; 기계 &gt; MH(공" +
            "조배관)</string>\r\n  <string>Drawing &gt; Start construction drawing/doc. &gt; 기계 &g" +
            "t; MP(위생배관)</string>\r\n  <string>Drawing &gt; Start construction drawing/doc. &gt" +
            "; 기계 &gt; MR(냉동냉장)</string>\r\n  <string>Drawing &gt; Start construction drawing/d" +
            "oc. &gt; 기계 &gt; MS(지열)</string>\r\n  <string>Drawing &gt; Start construction draw" +
            "ing/doc. &gt; 기계 &gt; MT(상세도)</string>\r\n  <string>Drawing &gt; Start constructio" +
            "n drawing/doc. &gt; 기계 &gt; MU(유틸리티가스)</string>\r\n  <string>Drawing &gt; Start co" +
            "nstruction drawing/doc. &gt; 소방 &gt; 소방기계</string>\r\n  <string>Drawing &gt; Start" +
            " construction drawing/doc. &gt; 소방 &gt; 소방전기</string>\r\n  <string>Drawing &gt; St" +
            "art construction drawing/doc. &gt; 전기</string>\r\n  <string>Drawing &gt; Start con" +
            "struction drawing/doc. &gt; 조경</string>\r\n  <string>Drawing &gt; Start constructi" +
            "on drawing/doc. &gt; 조경 &gt; 00 X-REF이미지</string>\r\n  <string>Drawing &gt; Start " +
            "construction drawing/doc. &gt; 토목</string>\r\n  <string>Drawing &gt; Start constru" +
            "ction drawing/doc. &gt; 통신</string>\r\n  <string>Material &gt; 검측요청서 &gt; 무선통신 보조설" +
            "비 공사</string>\r\n  <string>VE Report</string>\r\n  <string>설계문서 &gt; RFI</string>\r\n " +
            " <string>설계문서 &gt; 설계변경</string>\r\n  <string>설계변경요청서</string>\r\n  <string>임시양식</st" +
            "ring>\r\n  <string>주요공정사진</string>\r\n  <string>회의록</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection register_type {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["register_type"]));
            }
            set {
                this["register_type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("register")]
        public string register_folder_uri {
            get {
                return ((string)(this["register_folder_uri"]));
            }
            set {
                this["register_folder_uri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data/archive.db")]
        public string sqlite_db_location {
            get {
                return ((string)(this["sqlite_db_location"]));
            }
            set {
                this["sqlite_db_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sqlite")]
        public string db_type {
            get {
                return ((string)(this["db_type"]));
            }
            set {
                this["db_type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ko_KR")]
        public string language {
            get {
                return ((string)(this["language"]));
            }
            set {
                this["language"] = value;
            }
        }
    }
}
