//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pmis.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dev.sangah.com")]
        public string pmis_api_url {
            get {
                return ((string)(this["pmis_api_url"]));
            }
            set {
                this["pmis_api_url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GLB_PMIS")]
        public string pmis_project_code {
            get {
                return ((string)(this["pmis_project_code"]));
            }
            set {
                this["pmis_project_code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123456")]
        public string pmis_auth_key {
            get {
                return ((string)(this["pmis_auth_key"]));
            }
            set {
                this["pmis_auth_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string />
  <string>Genaral(일반)</string>
  <string>Architectural (건축)</string>
  <string>Structural (구조)</string>
  <string>Civil (토목)</string>
  <string>Landscaping (조경)</string>
  <string>Mechanical (기계)</string>
  <string>Electrical (전기)</string>
  <string>Communication (통신)</string>
  <string>Firefighting (소방)</string>
  <string>Other (기타)</string>
  <string>Architecture</string>
  <string>Civil</string>
  <string>Electrical</string>
  <string>FireFighting</string>
  <string>HSE</string>
  <string>Instrument</string>
  <string>Mechanical</string>
  <string>Piping</string>
  <string>Quality</string>
  <string>Process</string>
  <string>Structure</string>
  <string>Common</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection register_discipline {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["register_discipline"]));
            }
            set {
                this["register_discipline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string />
  <string>Draft(임시)</string>
  <string>For Information(정보)</string>
  <string>For Review(검토)</string>
  <string>For Approval(승인)</string>
  <string>Final(최종)</string>
  <string>As-Built(준공)</string>
  <string>No Longer In Use(폐기)</string>
  <string>승인용</string>
  <string>공사용</string>
  <string>참고용</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection register_status {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["register_status"]));
            }
            set {
                this["register_status"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring />\r\n  <string>#501동 </string>\r\n  <string>#501동 A-ZONE(구조)</string>\r\n  <str" +
            "ing>#501동 B-ZONE(구조)</string>\r\n  <string>#501동 C-ZONE(구조)</string>\r\n  <string>#5" +
            "01동 D-ZONE(구조)</string>\r\n  <string>#501동 세대(마감)</string>\r\n  <string>#501동 외벽(마감)" +
            "</string>\r\n  <string>#501동 지붕층(마감)</string>\r\n  <string>#501동 코어#1(마감)</string>\r\n" +
            "  <string>#501동 코어#2(마감)</string>\r\n  <string>#501동 필로티(마감)</string>\r\n  <string>#" +
            "502동</string>\r\n  <string>#502동 A-ZONE(구조)</string>\r\n  <string>#502동 B-ZONE(구조)</" +
            "string>\r\n  <string>#502동 D-ZONE(구조)</string>\r\n  <string>#502동 세대(마감)</string>\r\n " +
            " <string>#502동 외벽(마감)</string>\r\n  <string>#502동 지붕층(마감)</string>\r\n  <string>#502" +
            "동 코어#1(마감)</string>\r\n  <string>#502동 코어#2(마감)</string>\r\n  <string>#502동 필로티(마감)<" +
            "/string>\r\n  <string>#502동C-ZONE(구조)</string>\r\n  <string>#503동 </string>\r\n  <stri" +
            "ng>#503동 A-ZONE(구조)</string>\r\n  <string>#503동 B-ZONE(구조)</string>\r\n  <string>#50" +
            "3동 C-ZONE(구조)</string>\r\n  <string>#503동 D-ZONE(구조)</string>\r\n  <string>#503동 세대(" +
            "마감)</string>\r\n  <string>#503동 외벽(마감)</string>\r\n  <string>#503동 지붕층(마감)</string>\r" +
            "\n  <string>#503동 코어#1(마감)</string>\r\n  <string>#503동 코어#2(마감)</string>\r\n  <string" +
            ">#503동 필로티(마감)</string>\r\n  <string>#504동 </string>\r\n  <string>#504동 A-ZONE(구조)</" +
            "string>\r\n  <string>#504동 B-ZONE(구조)</string>\r\n  <string>#504동 세대(마감)</string>\r\n " +
            " <string>#504동 외벽(마감)</string>\r\n  <string>#504동 지붕층(마감)</string>\r\n  <string>#504" +
            "동 코어#1(마감)</string>\r\n  <string>#504동 코어#2(마감)</string>\r\n  <string>#504동 필로티(마감)<" +
            "/string>\r\n  <string>#505동</string>\r\n  <string>#505동 A-ZONE(구조)</string>\r\n  <stri" +
            "ng>#505동 B-ZONE(구조)</string>\r\n  <string>#505동 C-ZONE(구조)</string>\r\n  <string>#50" +
            "5동 D-ZONE(구조)</string>\r\n  <string>#505동 세대(마감)</string>\r\n  <string>#505동 외벽(마감)<" +
            "/string>\r\n  <string>#505동 지붕층(마감)</string>\r\n  <string>#505동 코어#1(마감)</string>\r\n " +
            " <string>#505동 코어#2(마감)</string>\r\n  <string>#505동 필로티(마감)</string>\r\n  <string>1-" +
            "1호선</string>\r\n  <string>1-2호선</string>\r\n  <string>1. MAIN PAGE</string>\r\n  <stri" +
            "ng>1. 계약관리</string>\r\n  <string>1. 공정현황</string>\r\n  <string>1. 공지사항</string>\r\n  <" +
            "string>1. 문서일반</string>\r\n  <string>1. 사업현황</string>\r\n  <string>1. 시공업무보고</string" +
            ">\r\n  <string>1. 시스템 개요</string>\r\n  <string>1. 품질관리</string>\r\n  <string>2. 공통기능</" +
            "string>\r\n  <string>2. 문서관리</string>\r\n  <string>2. 분류체계</string>\r\n  <string>2. 사업" +
            "일정</string>\r\n  <string>2. 시스템 구성</string>\r\n  <string>2. 안전관리</string>\r\n  <string" +
            ">2. 조직현황</string>\r\n  <string>2. 하도급관리</string>\r\n  <string>2호선</string>\r\n  <strin" +
            "g>3-Months Shedule</string>\r\n  <string>3-Weeks Schedule</string>\r\n  <string>3. 공" +
            "정계획관리</string>\r\n  <string>3. 비상연락망</string>\r\n  <string>3. 사업현안</string>\r\n  <stri" +
            "ng>3. 시스템 시작하기</string>\r\n  <string>3. 원가(내역)관리</string>\r\n  <string>3. 제출물관리</str" +
            "ing>\r\n  <string>3. 환경관리</string>\r\n  <string>3호선</string>\r\n  <string>4. 공정진도관리</s" +
            "tring>\r\n  <string>4. 기성관리</string>\r\n  <string>4. 설계자료</string>\r\n  <string>4. 시공공" +
            "정사진</string>\r\n  <string>4. 웹하드</string>\r\n  <string>4호선</string>\r\n  <string>5. CM" +
            "IS 질의/응답</string>\r\n  <string>5. 공정승인관리</string>\r\n  <string>5. 월간시공보고</string>\r\n " +
            " <string>501동외부</string>\r\n  <string>502동외부</string>\r\n  <string>503동외부</string>\r\n" +
            "  <string>504동외부</string>\r\n  <string>505동외부</string>\r\n  <string>6. 주간시공보고</strin" +
            "g>\r\n  <string>ABS수지원형환기구 설치공사</string>\r\n  <string>Agreement contents management " +
            "document</string>\r\n  <string>Architectural</string>\r\n  <string>Architectural(건축)" +
            "</string>\r\n  <string>Architecture</string>\r\n  <string>Architecture (건축)</string>" +
            "\r\n  <string>Auxiliary equipment</string>\r\n  <string>Basic design drawing/doc.</s" +
            "tring>\r\n  <string>Boiler</string>\r\n  <string>CATV설비공사</string>\r\n  <string>Change" +
            " of design(설계변경도면/도서)</string>\r\n  <string>Civil</string>\r\n  <string>Civil &amp; " +
            "Archi</string>\r\n  <string>Civil (토목)</string>\r\n  <string>Civil(토목)</string>\r\n  <" +
            "string>Common (공통)</string>\r\n  <string>Community(커뮤니티)</string>\r\n  <string>Compl" +
            "etion drawing(준공도면)</string>\r\n  <string>Construction Change Direction</string>\r\n" +
            "  <string>Construction Management(시공관리)</string>\r\n  <string>Construction details" +
            " progress chart</string>\r\n  <string>Construction work report</string>\r\n  <string" +
            ">Contract Management</string>\r\n  <string>Contract design drawing/doc.</string>\r\n" +
            "  <string>Contract document</string>\r\n  <string>Contractor (시공사)</string>\r\n  <st" +
            "ring>Control</string>\r\n  <string>Correction Action Request (CAR)</string>\r\n  <st" +
            "ring>Daily Health and Safety Training Report</string>\r\n  <string>Daily construct" +
            "ion work report</string>\r\n  <string>Daily environment inspection report</string>" +
            "\r\n  <string>Daily environmental education report</string>\r\n  <string>Daily safet" +
            "y Inspection report</string>\r\n  <string>Daily work report</string>\r\n  <string>Da" +
            "ta Management</string>\r\n  <string>Deficiency Notice / Remedial Report</string>\r\n" +
            "  <string>Design Management</string>\r\n  <string>Design VE</string>\r\n  <string>De" +
            "sign VE/Data</string>\r\n  <string>Design VE/Report</string>\r\n  <string>Design cha" +
            "nge document</string>\r\n  <string>Design change notice (DCN)</string>\r\n  <string>" +
            "Design drawing/doc.</string>\r\n  <string>Design meeting(설계회의)</string>\r\n  <string" +
            ">Document Management</string>\r\n  <string>Documents &amp; Drawings</string>\r\n  <s" +
            "tring>E-Book Management(전자도서관리)</string>\r\n  <string>E.J마감공사</string>\r\n  <string>" +
            "Electrical/Communication</string>\r\n  <string>Electrical/Communication(전기/통신)</st" +
            "ring>\r\n  <string>Electricity</string>\r\n  <string>Electricity (전기)</string>\r\n  <s" +
            "tring>Electricity Power</string>\r\n  <string>Enforcement design 100%(실시설계(100%)도면" +
            "/도서)</string>\r\n  <string>Enforcement design 50%(실시설계(50%)도면/도서)</string>\r\n  <str" +
            "ing>Environmental Management</string>\r\n  <string>Environmental Management Plan</" +
            "string>\r\n  <string>Environmental visibility requirements</string>\r\n  <string>Equ" +
            "ipment manufacturers (자재/장비 제조업체)</string>\r\n  <string>Etc.</string>\r\n  <string>E" +
            "tcetera</string>\r\n  <string>Event Photos</string>\r\n  <string>Factory demolition " +
            "work</string>\r\n  <string>Fence installing construction</string>\r\n  <string>Field" +
            " Instruction</string>\r\n  <string>Field change notification (FCN)</string>\r\n  <st" +
            "ring>Field change request (FCR)</string>\r\n  <string>Fire</string>\r\n  <string>Fir" +
            "e </string>\r\n  <string>Firefighting</string>\r\n  <string>Firefighting(소방)</string" +
            ">\r\n  <string>Functional Breakdown Structure</string>\r\n  <string>HOOK설치공사</string" +
            ">\r\n  <string>History of usge of environment preservation cost </string>\r\n  <stri" +
            "ng>I. 시스템 개요</string>\r\n  <string>II.시스템공통</string>\r\n  <string>III.사업일반</string>\r" +
            "\n  <string>IV.계약/기성</string>\r\n  <string>IX. 문서/자료</string>\r\n  <string>Imported M" +
            "aterials Inspection</string>\r\n  <string>Information and Communication</string>\r\n" +
            "  <string>Initiation inspection bowel management</string>\r\n  <string>Inspection<" +
            "/string>\r\n  <string>Inspection Level 2</string>\r\n  <string>Inspection Level 3</s" +
            "tring>\r\n  <string>Inspection procedures / plans</string>\r\n  <string>LPG 저장시설공사</" +
            "string>\r\n  <string>Landscaping</string>\r\n  <string>Landscaping(조경)</string>\r\n  <" +
            "string>Letter</string>\r\n  <string>MDF실 마감공사</string>\r\n  <string>Machine</string>" +
            "\r\n  <string>Machine (기계)</string>\r\n  <string>Machine(기계)</string>\r\n  <string>Mas" +
            "ter Plan(사업계획)</string>\r\n  <string>Material Approved Request</string>\r\n  <string" +
            ">Materials for meeting</string>\r\n  <string>Measurement</string>\r\n  <string>Measu" +
            "res for delay</string>\r\n  <string>Meeting Minutes</string>\r\n  <string>Minutes(회의" +
            "록)</string>\r\n  <string>Monthly foreground photo</string>\r\n  <string>Monthly work" +
            " report</string>\r\n  <string>Non Conformance Report </string>\r\n  <string>Nonconfo" +
            "rmity reports (NCR)</string>\r\n  <string>Office Remodeling</string>\r\n  <string>Of" +
            "ficial Documents</string>\r\n  <string>On-site inspection (ITP)</string>\r\n  <strin" +
            "g>Organization</string>\r\n  <string>Other</string>\r\n  <string>Other Management(기타" +
            "관리)</string>\r\n  <string>Other construction</string>\r\n  <string>Other work report" +
            "</string>\r\n  <string>Other(기타)</string>\r\n  <string>PMIS 구축방안 Setting</string>\r\n " +
            " <string>PMIS구축비</string>\r\n  <string>Permission</string>\r\n  <string>Pre-construc" +
            "tion work report</string>\r\n  <string>Process Management(공정관리)</string>\r\n  <strin" +
            "g>Process photo</string>\r\n  <string>Production process photo</string>\r\n  <string" +
            ">Project Management</string>\r\n  <string>Project Status</string>\r\n  <string>Proje" +
            "ct Status(사업일반)</string>\r\n  <string>Promotional materials (홍보자료)</string>\r\n  <st" +
            "ring>Quality Diagnostic (품질진단)</string>\r\n  <string>Quality Improvement Program(Q" +
            "IP)</string>\r\n  <string>Quality Management</string>\r\n  <string>Quality Managemen" +
            "t Plan</string>\r\n  <string>Quality Manual (품질 메뉴얼)</string>\r\n  <string>Quality p" +
            "rocedures (품질절차서)</string>\r\n  <string>Quality reference room (품질 자료실)</string>\r\n" +
            "  <string>Quality/Safety/Environment(품질/안전/환경)</string>\r\n  <string>RM13~RM18</st" +
            "ring>\r\n  <string>RM19~RM22</string>\r\n  <string>RM1~RM6</string>\r\n  <string>RM23~" +
            "RM27</string>\r\n  <string>RM28~RM29</string>\r\n  <string>RM30~RM38</string>\r\n  <st" +
            "ring>RM39~RM46</string>\r\n  <string>RM47~RM54</string>\r\n  <string>RM55~RM59</stri" +
            "ng>\r\n  <string>RM60~RM63</string>\r\n  <string>RM64~RM65</string>\r\n  <string>RM66~" +
            "RM67</string>\r\n  <string>RM68~RM74</string>\r\n  <string>RM75~RM82</string>\r\n  <st" +
            "ring>RM7~RM12</string>\r\n  <string>RM83~RM86</string>\r\n  <string>RM87~RM88</strin" +
            "g>\r\n  <string>Report Management(보고관리)</string>\r\n  <string>Report material(보고자료)<" +
            "/string>\r\n  <string>Request For Design Change</string>\r\n  <string>Request For In" +
            "formation</string>\r\n  <string>Request For Inspection</string>\r\n  <string>Request" +
            " for Information</string>\r\n  <string>SM16~SM22</string>\r\n  <string>SM1~SM8</stri" +
            "ng>\r\n  <string>SM23~SM30</string>\r\n  <string>SM31~SM33</string>\r\n  <string>SM34~" +
            "SM43</string>\r\n  <string>SM44~SM50</string>\r\n  <string>SM51~SM53</string>\r\n  <st" +
            "ring>SM54~SM59</string>\r\n  <string>SM60~SM65</string>\r\n  <string>SM66~SM69</stri" +
            "ng>\r\n  <string>SM70~SM76</string>\r\n  <string>SM9~SM15</string>\r\n  <string>Safety" +
            " Corrective Action Request </string>\r\n  <string>Safety Management</string>\r\n  <s" +
            "tring>Safety Management Plan</string>\r\n  <string>Safety Resources</string>\r\n  <s" +
            "tring>Safety intellectual</string>\r\n  <string>Safety management usage</string>\r\n" +
            "  <string>Site Memo</string>\r\n  <string>Start construction drawing/doc.</string>" +
            "\r\n  <string>Status of defects per company</string>\r\n  <string>Status of the even" +
            "t of a disaster</string>\r\n  <string>Structural</string>\r\n  <string>Structural(구조" +
            ")</string>\r\n  <string>Subcontract   Databank</string>\r\n  <string>Subcontract App" +
            "roval Request</string>\r\n  <string>Submittal</string>\r\n  <string>Supervision vaca" +
            "tion.</string>\r\n  <string>Supervision work report</string>\r\n  <string>Supervisio" +
            "n work report (Fire)</string>\r\n  <string>Supervision work report (Mechanical)</s" +
            "tring>\r\n  <string>Supervision work report(Civil &amp; archi)</string>\r\n  <string" +
            ">Supervision work report(Electricity)</string>\r\n  <string>Supervision work repor" +
            "t(Information and Communicat</string>\r\n  <string>Supervision work report(N1)</st" +
            "ring>\r\n  <string>Supervision work report(N2)</string>\r\n  <string>Supervision wor" +
            "k report(electric)</string>\r\n  <string>Supervisor Official writing</string>\r\n  <" +
            "string>Supplier default disposal requests (SDDR)</string>\r\n  <string>System Manu" +
            "al</string>\r\n  <string>T.A.B</string>\r\n  <string>T.A.B 및 시운전</string>\r\n  <string" +
            ">Technical Review Comments</string>\r\n  <string>The-spot inspection report</strin" +
            "g>\r\n  <string>Transmittal</string>\r\n  <string>Transmittal For Approval</string>\r" +
            "\n  <string>Turbine</string>\r\n  <string>UPS설치공사</string>\r\n  <string>V.공정관리</strin" +
            "g>\r\n  <string>VI.시공관리</string>\r\n  <string>VII.보고관리</string>\r\n  <string>VIII.커뮤니티" +
            "</string>\r\n  <string>Waste Management document</string>\r\n  <string>Work order (O" +
            "wner)</string>\r\n  <string>Work order (Supervisor)</string>\r\n  <string>Workflow T" +
            "ransmittal</string>\r\n  <string>Writing Official document (Shinhan)</string>\r\n  <" +
            "string>ㅈ</string>\r\n  <string>가구공사</string>\r\n  <string>가구류 반입</string>\r\n  <string" +
            ">가배수로공사</string>\r\n  <string>가설건물공사</string>\r\n  <string>가설건축물공사</string>\r\n  <stri" +
            "ng>가설공사</string>\r\n  <string>가설사무소 축조신고</string>\r\n  <string>가설수도료</string>\r\n  <st" +
            "ring>가설시설물 설치 및 철거계획서</string>\r\n  <string>가설시설물공사</string>\r\n  <string>가설용수 신청</s" +
            "tring>\r\n  <string>가설장비공사</string>\r\n  <string>가설전기 인입신청</string>\r\n  <string>가설전기료" +
            "</string>\r\n  <string>가설전화 인입신청</string>\r\n  <string>가스설비공사</string>\r\n  <string>각동" +
            "옥외부</string>\r\n  <string>각종 보고 형식 Setting</string>\r\n  <string>간접노무비</string>\r\n  <" +
            "string>간접비</string>\r\n  <string>강재창호설치공사</string>\r\n  <string>강재창호틀설치공사</string>\r\n" +
            "  <string>강화유리공사</string>\r\n  <string>강화유리위실크스크린인쇄공사</string>\r\n  <string>거실등박스설치<" +
            "/string>\r\n  <string>건물경관조명공사</string>\r\n  <string>건물지하접지공사</string>\r\n  <string>건설" +
            "</string>\r\n  <string>건설공사표지공사</string>\r\n  <string>건설사업관리 기록부</string>\r\n  <string" +
            ">건설사업관리 지시부</string>\r\n  <string>건설사업관리 지시부 조치</string>\r\n  <string>건설정보시스템공사</str" +
            "ing>\r\n  <string>건식 AD 및 PD설치공사</string>\r\n  <string>건축공사</string>\r\n  <string>걸레받이" +
            "설치공사</string>\r\n  <string>검침설비공사</string>\r\n  <string>견본</string>\r\n  <string>견적비</" +
            "string>\r\n  <string>경계측량의뢰</string>\r\n  <string>경량기포콘크리트타설공사</string>\r\n  <string>경" +
            "량벽체설치공사</string>\r\n  <string>경로당 마감공사</string>\r\n  <string>경비동</string>\r\n  <string" +
            ">경비실#1 마감공사</string>\r\n  <string>경비실#2 마감공사</string>\r\n  <string>계단난간설치공사</string>" +
            "\r\n  <string>계약자 및 발주처 사전점검</string>\r\n  <string>계약자 사전점검</string>\r\n  <string>계측공사" +
            "</string>\r\n  <string>고정식배기구설치공사</string>\r\n  <string>골프연습장 마감공사</string>\r\n  <stri" +
            "ng>공기조화설비공사</string>\r\n  <string>공동구</string>\r\n  <string>공동구 #1</string>\r\n  <stri" +
            "ng>공동구 #2</string>\r\n  <string>공동구 #3</string>\r\n  <string>공동구 #4</string>\r\n  <str" +
            "ing>공동구배관공사</string>\r\n  <string>공동구전기공사</string>\r\n  <string>공무행정제출물</string>\r\n  " +
            "<string>공사 착공신고서</string>\r\n  <string>공사관련제출물</string>\r\n  <string>공사단계</string>\r\n" +
            "  <string>공사일지</string>\r\n  <string>공사진행단계제출물</string>\r\n  <string>공사표지</string>\r\n" +
            "  <string>공용부위 환기설비공사</string>\r\n  <string>공정보고</string>\r\n  <string>공조장비설치공사</str" +
            "ing>\r\n  <string>공종 표준분류</string>\r\n  <string>공통</string>\r\n  <string>공통가설공사</strin" +
            "g>\r\n  <string>관리사무소 마감공사</string>\r\n  <string>관리실</string>\r\n  <string>관목식재 지반조성공사" +
            "</string>\r\n  <string>관목식재공사-낙엽관목</string>\r\n  <string>관목식재공사-상록관목/대형관목</string>\r\n" +
            "  <string>관수공사</string>\r\n  <string>교목식재 지방조성공사</string>\r\n  <string>교목식재공사-낙엽교목 R" +
            "12 이하</string>\r\n  <string>교목식재공사-낙엽교목 R15~40</string>\r\n  <string>교목식재공사-상록교목</st" +
            "ring>\r\n  <string>교목식재공사-소나무 파트1</string>\r\n  <string>교목식재공사-소나무 파트2</string>\r\n  <" +
            "string>교통안전시설공사-100%완료</string>\r\n  <string>교통안전시설공사-중기60%완료</string>\r\n  <string>" +
            "교통안전시설공사-초기30%완료</string>\r\n  <string>구매관리</string>\r\n  <string>구조물 되메우기공사(지하1층)-1" +
            "00%완료</string>\r\n  <string>구조물 되메우기공사(지하1층)-중기50%완료</string>\r\n  <string>구조물 되메우기공" +
            "사(지하1층)-중후기80%완</string>\r\n  <string>구조물 되메우기공사(지하1층)-초기30%완료</string>\r\n  <string" +
            ">구조물 되메우기공사(지하2층)-100%완료</string>\r\n  <string>구조물 되메우기공사(지하2층)-중기50%완료</string>\r\n" +
            "  <string>구조물 되메우기공사(지하2층)-중후기80%완</string>\r\n  <string>구조물 되메우기공사(지하2층)-초기30%완료<" +
            "/string>\r\n  <string>구조물 되메우기공사(지하3층)-100%완료</string>\r\n  <string>구조물 되메우기공사(지하3층)" +
            "-중기50%완료</string>\r\n  <string>구조물 되메우기공사(지하3층)-중후기80%완</string>\r\n  <string>구조물 되메" +
            "우기공사(지하3층)-초기30%완료</string>\r\n  <string>구조물토공사</string>\r\n  <string>구조물토공사(외부반출토-사" +
            "질토)-100%완료</string>\r\n  <string>구조물토공사(외부반출토-사질토)-중기50%</string>\r\n  <string>구조물토공" +
            "사(외부반출토-사질토)-중후기80</string>\r\n  <string>구조물토공사(외부반출토-사질토)-초기30%</string>\r\n  <stri" +
            "ng>구조물토공사(외부반출토-암반)-100%완료</string>\r\n  <string>구조물토공사(외부반출토-암반)-중기50%완</string>\r" +
            "\n  <string>구조물토공사(외부반출토-암반)-중후기80%</string>\r\n  <string>구조물토공사(외부반출토-암반)-초기30%완</" +
            "string>\r\n  <string>구조물토공사(절토-사질토)-100%완료</string>\r\n  <string>구조물토공사(절토-사질토)-중기50" +
            "%완료</string>\r\n  <string>구조물토공사(절토-사질토)-중후기80%완료</string>\r\n  <string>구조물토공사(절토-사질" +
            "토)-초기30%완료</string>\r\n  <string>구조물토공사(절토-암반)-100%완료</string>\r\n  <string>구조물토공사(절" +
            "토-암반)-중기50%완료</string>\r\n  <string>구조물토공사(절토-암반)-중후기80%완료</string>\r\n  <string>구조물" +
            "토공사(절토-암반)-초기30%완료</string>\r\n  <string>구조물토공사(현장내운반토)-100%완료</string>\r\n  <string" +
            ">구조물토공사(현장내운반토)-중기50%완료</string>\r\n  <string>구조물토공사(현장내운반토)-중후기80%완료</string>\r\n  " +
            "<string>구조물토공사(현장내운반토)-초기30%완료</string>\r\n  <string>구조체 양생</string>\r\n  <string>구조" +
            "체 타설</string>\r\n  <string>구조체가설공사 동바리설치공사</string>\r\n  <string>구조체가설공사 시스템동바리설치공사<" +
            "/string>\r\n  <string>구조체가설공사(보양 등)</string>\r\n  <string>굴토공사 착공신고</string>\r\n  <str" +
            "ing>그래픽/로고도장공사</string>\r\n  <string>근리생활시설</string>\r\n  <string>근린생활시설</string>\r\n " +
            " <string>근린생활시설 마감공사</string>\r\n  <string>금속공사</string>\r\n  <string>금속기와경사지붕공사</st" +
            "ring>\r\n  <string>급수간선공사(관로공사)</string>\r\n  <string>급수간선공사(토공사)</string>\r\n  <strin" +
            "g>급수배관공사</string>\r\n  <string>급수배관공사(수직)</string>\r\n  <string>급수배관공사(수평)</string>\r" +
            "\n  <string>급탕배관공사</string>\r\n  <string>급탕배관공사(수직)</string>\r\n  <string>급탕배관공사(수평)<" +
            "/string>\r\n  <string>기계공사</string>\r\n  <string>기계배관자재반입</string>\r\n  <string>기계실</s" +
            "tring>\r\n  <string>기계실배관공사</string>\r\n  <string>기계실소화배관</string>\r\n  <string>기계장비반입" +
            "</string>\r\n  <string>기계지급자재반입</string>\r\n  <string>기공식 관련</string>\r\n  <string>기구부" +
            "착공사</string>\r\n  <string>기구취부공사</string>\r\n  <string>기성 및 준공 검사원</string>\r\n  <stri" +
            "ng>기성 청구 형식 Setting</string>\r\n  <string>기술검토의견서</string>\r\n  <string>기자재제작사진</str" +
            "ing>\r\n  <string>기초</string>\r\n  <string>기초과학연구원 양식</string>\r\n  <string>기타</string" +
            ">\r\n  <string>기타 가설공사</string>\r\n  <string>기타 잡공사</string>\r\n  <string>기타 장비공사</str" +
            "ing>\r\n  <string>기타공사</string>\r\n  <string>기타금속공사</string>\r\n  <string>기타난간설치공사</st" +
            "ring>\r\n  <string>기타미장공사</string>\r\n  <string>기타유리공사</string>\r\n  <string>기타전기공사</s" +
            "tring>\r\n  <string>기타정보통신공사</string>\r\n  <string>낙서방지용 페인트칠</string>\r\n  <string>난방" +
            "배관공사</string>\r\n  <string>난방배관공사(수직)</string>\r\n  <string>난방배관공사수평)</string>\r\n  <s" +
            "tring>내부수성 벽 페인트공사</string>\r\n  <string>내부수성 천장 페인트공사</string>\r\n  <string>노출배관공사<" +
            "/string>\r\n  <string>놀이시설물 공사</string>\r\n  <string>놀이시설물 공사-100%완료(원앤티에스)</string>" +
            "\r\n  <string>놀이시설물 공사-초기50%완료(가이아글로)</string>\r\n  <string>다짐공사</string>\r\n  <string" +
            ">단독정화조 설치신고</string>\r\n  <string>단열공사</string>\r\n  <string>단위세대전등전열공사</string>\r\n  " +
            "<string>단지경관조명공사</string>\r\n  <string>단지외곽섹터</string>\r\n  <string>단지주도로</string>\r\n" +
            "  <string>대 관공서업무</string>\r\n  <string>대 발주처업무</string>\r\n  <string>대지조성토공사</strin" +
            "g>\r\n  <string>덕트설비공사</string>\r\n  <string>도로점용 허가신청</string>\r\n  <string>도막방수공사</s" +
            "tring>\r\n  <string>도장공사</string>\r\n  <string>돌쌓기공사-완료</string>\r\n  <string>돌쌓기공사-초기" +
            "50%완료</string>\r\n  <string>동력반설치공사</string>\r\n  <string>동절기공사관련비</string>\r\n  <stri" +
            "ng>등기구반입</string>\r\n  <string>로이복층유리(아르곤)공사</string>\r\n  <string>로이복층유리공사</string>" +
            "\r\n  <string>마감가설공사 먹메김</string>\r\n  <string>마감가설공사(보양 등)</string>\r\n  <string>마감자재" +
            "반입</string>\r\n  <string>마루깔기공사</string>\r\n  <string>마일스톤</string>\r\n  <string>마일스톤1" +
            "</string>\r\n  <string>마일스톤1_1</string>\r\n  <string>마일스톤1_1_1</string>\r\n  <string>말" +
            "뚝박기공사</string>\r\n  <string>말뚝뽑기공사</string>\r\n  <string>매입배관공사</string>\r\n  <string>" +
            "멀티프로그램실 마감공사</string>\r\n  <string>메쉬LOUVER설치공사</string>\r\n  <string>목공사</string>\r\n" +
            "  <string>목재데크깔기(휴게공간)공사</string>\r\n  <string>목재루버설치공사</string>\r\n  <string>목재벤치설치" +
            "공사</string>\r\n  <string>목재창호설치공사</string>\r\n  <string>목재창호틀설치공사</string>\r\n  <strin" +
            "g>목조칸막이벽설치공사</string>\r\n  <string>무근콘크리트공사</string>\r\n  <string>무동력고정식흡출기설치공사</str" +
            "ing>\r\n  <string>무선통보조설비공사</string>\r\n  <string>무선통신 보조설비 공사</string>\r\n  <string>무" +
            "인경비시스템공사</string>\r\n  <string>무인택배시스템 설치공사</string>\r\n  <string>무재해 개시신고</string>\r" +
            "\n  <string>문서고 마감공사</string>\r\n  <string>물가연동비</string>\r\n  <string>미장공사</string>\r" +
            "\n  <string>바닥 석공사</string>\r\n  <string>반자돌림설치설치공사</string>\r\n  <string>반침장설치공사</st" +
            "ring>\r\n  <string>발열선 설치공사</string>\r\n  <string>발전기설치공사</string>\r\n  <string>발전기실</" +
            "string>\r\n  <string>발주처 사전점검</string>\r\n  <string>발코니바닥드레인공사</string>\r\n  <string>발" +
            "코니바닥타일공사</string>\r\n  <string>발코니샷시설치공사</string>\r\n  <string>방송설비공사</string>\r\n  <s" +
            "tring>방수공사</string>\r\n  <string>방수자재반입</string>\r\n  <string>방재실 마감공사</string>\r\n  <" +
            "string>배관공사</string>\r\n  <string>배관배선공사</string>\r\n  <string>배관주위몰탈충진</string>\r\n  " +
            "<string>배선공사</string>\r\n  <string>배수공사</string>\r\n  <string>배수공사(건물우수관연결공사)-100%완료" +
            "</string>\r\n  <string>배수공사(건물우수관연결공사)-중기60%완료</string>\r\n  <string>배수공사(건물우수관연결공사)" +
            "-초기30%완료</string>\r\n  <string>배수공사(구조물및관로공사)</string>\r\n  <string>배수공사(빗물받이및연결관공사)" +
            "-100%완료</string>\r\n  <string>배수공사(빗물받이및연결관공사)-중기55%완</string>\r\n  <string>배수공사(빗물받" +
            "이및연결관공사)-중후기80%</string>\r\n  <string>배수공사(빗물받이및연결관공사)-초기30%완</string>\r\n  <string>" +
            "배수공사(집수정및연결관공사)-100%완료</string>\r\n  <string>배수공사(집수정및연결관공사)-중기55%완료</string>\r\n  <" +
            "string>배수공사(집수정및연결관공사)-중후기80%완</string>\r\n  <string>배수공사(집수정및연결관공사)-초기30%완료</stri" +
            "ng>\r\n  <string>배수공사(측구및플륨관공사)-100%완료</string>\r\n  <string>배수공사(측구및플륨관공사)-중기55%완료<" +
            "/string>\r\n  <string>배수공사(측구및플륨관공사)-중후기80%완료</string>\r\n  <string>배수공사(측구및플륨관공사)-초" +
            "기30%완료</string>\r\n  <string>배수공사(토공사)</string>\r\n  <string>배수공사섹터</string>\r\n  <str" +
            "ing>배수판설치공사</string>\r\n  <string>벽 도배공사</string>\r\n  <string>벽 석공사</string>\r\n  <st" +
            "ring>벽돌공사</string>\r\n  <string>벽체단열재붙이기공사</string>\r\n  <string>벽체스치로폴넣기공사</string>" +
            "\r\n  <string>변전실배관배선공사</string>\r\n  <string>변전실전기공사</string>\r\n  <string>보도</string" +
            ">\r\n  <string>보도경계석설치공사-100%완료</string>\r\n  <string>보도경계석설치공사-중기55%완료</string>\r\n  " +
            "<string>보도경계석설치공사-중후기80%완료</string>\r\n  <string>보도경계석설치공사-초기30%완료</string>\r\n  <st" +
            "ring>보안등설치공사</string>\r\n  <string>보양공사</string>\r\n  <string>보온공사(수직)</string>\r\n  <" +
            "string>보온공사(수평)</string>\r\n  <string>보육시설 마감공사</string>\r\n  <string>보차도경계석설치공사-100" +
            "%완료</string>\r\n  <string>보차도경계석설치공사-중기60%완료</string>\r\n  <string>보차도경계석설치공사-초기30%완" +
            "료</string>\r\n  <string>보차혼용도로</string>\r\n  <string>복도난간설치공사</string>\r\n  <string>복도" +
            "드레인공사</string>\r\n  <string>복지시설</string>\r\n  <string>복층유리공사</string>\r\n  <string>복합" +
            "단열재설치공사</string>\r\n  <string>부대공사철근콘크리트공사-100%완료</string>\r\n  <string>부대공사철근콘크리트공사" +
            "-30%완료</string>\r\n  <string>부대공사철근콘크리트공사-60%완료</string>\r\n  <string>부대복리시설</string" +
            ">\r\n  <string>부대시설공사-100%완료</string>\r\n  <string>부대시설공사-중기60%완료</string>\r\n  <strin" +
            "g>부대시설공사-초기30%완료</string>\r\n  <string>부속건물구조체공사</string>\r\n  <string>부속실 타일공사</str" +
            "ing>\r\n  <string>부스덕트공사</string>\r\n  <string>분야별 업무일자</string>\r\n  <string>블럭공사</st" +
            "ring>\r\n  <string>비닐장판깔기공사</string>\r\n  <string>비산분진 발생신고</string>\r\n  <string>비상차로" +
            "</string>\r\n  <string>비용일정관리계획서</string>\r\n  <string>비용일정관리비</string>\r\n  <string>비" +
            "준공검사 조치결과</string>\r\n  <string>비탈면보호공사</string>\r\n  <string>뿜칠도장공사</string>\r\n  <st" +
            "ring>사급자재</string>\r\n  <string>사다리설치공사</string>\r\n  <string>사인물공사</string>\r\n  <str" +
            "ing>상수도공사</string>\r\n  <string>생태복원녹화공사-인공토포설</string>\r\n  <string>생태복원녹화공사-종자포설</" +
            "string>\r\n  <string>샤워부스설치공사</string>\r\n  <string>석공사</string>\r\n  <string>석재 걸레받이설" +
            "치공사</string>\r\n  <string>석재 마루굽틀설치공사</string>\r\n  <string>석재 재료분리대설치공사</string>\r\n " +
            " <string>석재 젠다이설치공사</string>\r\n  <string>설계 변경 Flow Setting</string>\r\n  <string>설" +
            "계도서검토보고서</string>\r\n  <string>설계변경 승인 요청서</string>\r\n  <string>설계비</string>\r\n  <st" +
            "ring>성능시험 및 검사</string>\r\n  <string>세대 환기설비공사</string>\r\n  <string>세대내부난간설치공사</str" +
            "ing>\r\n  <string>세대내부시스템계단설치공사</string>\r\n  <string>소방전기설비공사</string>\r\n  <string>소" +
            "화가스 배관공사</string>\r\n  <string>소화기구류 공사</string>\r\n  <string>소화배관공사</string>\r\n  <st" +
            "ring>소화배관공사(수직)</string>\r\n  <string>소화배관공사(수평)</string>\r\n  <string>소화설비공사</strin" +
            "g>\r\n  <string>소화장비류 설치공사</string>\r\n  <string>쇠흙손마감공사</string>\r\n  <string>수경시설물공사" +
            "-구조체 및 방수공사</string>\r\n  <string>수경시설물공사-설비 및 마감공사</string>\r\n  <string>수배전반설치공사</" +
            "string>\r\n  <string>수신반설치공사</string>\r\n  <string>수장공사</string>\r\n  <string>수전류설치공사<" +
            "/string>\r\n  <string>순성토 포설 및 다짐-100%완료</string>\r\n  <string>순성토 포설 및 다짐-중기50%완료</" +
            "string>\r\n  <string>순성토 포설 및 다짐-중후기80%완료</string>\r\n  <string>순성토 포설 및 다짐-초기30%완료<" +
            "/string>\r\n  <string>스레인레스창호설치공사</string>\r\n  <string>스프링클러 배관공사(수직)</string>\r\n  <" +
            "string>스프링클러 배관공사(수평)</string>\r\n  <string>슬라이드셔터설치공사</string>\r\n  <string>승강기공사</" +
            "string>\r\n  <string>시공확인서</string>\r\n  <string>시멘트모르타르내벽바름공사</string>\r\n  <string>시" +
            "멘트모르타르바닥바름공사</string>\r\n  <string>시멘트모르타르외벽바름공사</string>\r\n  <string>시멘트액체방수공사</st" +
            "ring>\r\n  <string>시설 TURN-OVER</string>\r\n  <string>시설물분류</string>\r\n  <string>시설별 " +
            "정보통신공사</string>\r\n  <string>시스템가구설치공사</string>\r\n  <string>시스템설치공사</string>\r\n  <st" +
            "ring>시운전</string>\r\n  <string>시운전계획서</string>\r\n  <string>시트방수공사</string>\r\n  <stri" +
            "ng>시험</string>\r\n  <string>시험 </string>\r\n  <string>식재공사</string>\r\n  <string>식재부대공" +
            "사-100%완료</string>\r\n  <string>식재부대공사초기50%완료</string>\r\n  <string>식재유지관리공사</string>" +
            "\r\n  <string>신발장설치공사</string>\r\n  <string>실링공사</string>\r\n  <string>실외기실선반설치공사</str" +
            "ing>\r\n  <string>씰링재(유리고정용)공사</string>\r\n  <string>아스콘포장공사</string>\r\n  <string>아트월" +
            "설치공사</string>\r\n  <string>안전관리비 사용실적 보고 형식 Setting</string>\r\n  <string>안전관리자선임보고<" +
            "/string>\r\n  <string>안전난간설치설치공사</string>\r\n  <string>안전보건책임자 선임보고</string>\r\n  <str" +
            "ing>안테나설치공사</string>\r\n  <string>알루미늄합금재창호공사</string>\r\n  <string>암반검사원</string>\r\n" +
            "  <string>애칭유리공사</string>\r\n  <string>액체방수2차/폴리머방수2종+2종</string>\r\n  <string>에어컨 설" +
            "치공사</string>\r\n  <string>에폭시코팅</string>\r\n  <string>열교환실</string>\r\n  <string>열교환실설" +
            "비공사</string>\r\n  <string>염화비닐타일붙이기공사</string>\r\n  <string>예정비용일정공정표</string>\r\n  <s" +
            "tring>오배수 및 통기관배관공사(수직)</string>\r\n  <string>오배수 및 통기관배관공사(수평)</string>\r\n  <strin" +
            "g>오수공사(건물오수관연결공사)-100%완료</string>\r\n  <string>오수공사(건물오수관연결공사)-중기60%완료</string>\r\n " +
            " <string>오수공사(건물오수관연결공사)-초기30%완료</string>\r\n  <string>오수공사(오수관로 및 맨홀공사)</string>\r" +
            "\n  <string>오수공사(토공사)</string>\r\n  <string>오수공사섹터</string>\r\n  <string>오수정화시설 설치신고<" +
            "/string>\r\n  <string>옥내가스배관공사</string>\r\n  <string>옥외가스배관공사</string>\r\n  <string>옥외" +
            "배관배선공사</string>\r\n  <string>옥외소방간선공사</string>\r\n  <string>옥외소화배관</string>\r\n  <stri" +
            "ng>옥외시설</string>\r\n  <string>옥외자동제어공사</string>\r\n  <string>옥외전기공사</string>\r\n  <str" +
            "ing>옥외통신공사</string>\r\n  <string>온돌미장바닥단열공사</string>\r\n  <string>와이어메쉬설치공사</string>" +
            "\r\n  <string>완성검사</string>\r\n  <string>외벽보온틀설치공사</string>\r\n  <string>외부 비계공사</stri" +
            "ng>\r\n  <string>외부수성 벽 페인트공사</string>\r\n  <string>외부수성 천장 페인트공사</string>\r\n  <strin" +
            "g>욕실천장틀설치공사</string>\r\n  <string>우/오수공사</string>\r\n  <string>우레탄페인트(걸레받이)공사</strin" +
            "g>\r\n  <string>우레탄페인트공사</string>\r\n  <string>우편함설치공사</string>\r\n  <string>운반비</stri" +
            "ng>\r\n  <string>운전 및 유지 관리 지침서</string>\r\n  <string>운전 및 유지 관리 지침서 등</string>\r\n  <" +
            "string>원격검침설비공사</string>\r\n  <string>위생기구류반입</string>\r\n  <string>위생기구류설치</string>" +
            "\r\n  <string>위생기구류설치공사</string>\r\n  <string>위생도기류반입</string>\r\n  <string>위생도기류설치공사<" +
            "/string>\r\n  <string>위생도기설치공사</string>\r\n  <string>유도표시공사</string>\r\n  <string>유리공사" +
            "</string>\r\n  <string>유해,위임 방지계획서</string>\r\n  <string>인력터파기공사</string>\r\n  <string" +
            ">인조잔디깔기공사</string>\r\n  <string>인조화강석블록포장공사-100%완료</string>\r\n  <string>인조화강석블록포장공사" +
            "-중기60%완료</string>\r\n  <string>인조화강석블록포장공사-초기30%완료</string>\r\n  <string>인터폰설치공사</st" +
            "ring>\r\n  <string>일반경비</string>\r\n  <string>일반관리비/이윤</string>\r\n  <string>임시공급시설공사<" +
            "/string>\r\n  <string>임시물공급시설공사</string>\r\n  <string>임시전기공급시설공사</string>\r\n  <string" +
            ">입상배관배선공사</string>\r\n  <string>자동식세륜기설치비</string>\r\n  <string>자동제어설비공사</string>\r\n " +
            " <string>자동화재탐지설비공사</string>\r\n  <string>자재</string>\r\n  <string>자재 사용 승인 요청서 </st" +
            "ring>\r\n  <string>자재인양용리프트공사</string>\r\n  <string>잔디식재 지반조성공사</string>\r\n  <string>" +
            "잔디식재공사</string>\r\n  <string>장비설치공사</string>\r\n  <string>장비설치공사(기타)</string>\r\n  <st" +
            "ring>장식구조물설치공사</string>\r\n  <string>재료공급원 일람표</string>\r\n  <string>재료분리대설치공사</stri" +
            "ng>\r\n  <string>재료시험(구조체공사)</string>\r\n  <string>재료시험(마감공사)</string>\r\n  <string>저수" +
            "조</string>\r\n  <string>전기공사</string>\r\n  <string>전기기구반입</string>\r\n  <string>전기배관자재" +
            "반입</string>\r\n  <string>전기실</string>\r\n  <string>전기지급자재반입</string>\r\n  <string>전등설비" +
            "공사</string>\r\n  <string>전등제어설비공사</string>\r\n  <string>전력간선공사</string>\r\n  <string>전" +
            "력검침설비공사</string>\r\n  <string>전력비</string>\r\n  <string>전력인입공사</string>\r\n  <string>전" +
            "력제어설비공사</string>\r\n  <string>전열설비공사</string>\r\n  <string>전열제어설비공사</string>\r\n  <str" +
            "ing>전원인입공사</string>\r\n  <string>전층</string>\r\n  <string>전화인입공사</string>\r\n  <string" +
            ">점검구설치공사</string>\r\n  <string>점검사항 수정</string>\r\n  <string>점검사항수정</string>\r\n  <str" +
            "ing>점자표시판공사</string>\r\n  <string>접합강판설치공사</string>\r\n  <string>제거식소일네일공사-네일1,2단 완료" +
            "</string>\r\n  <string>제거식소일네일공사-네일3,4단 완료</string>\r\n  <string>제거식소일네일공사-네일5,6단 완료" +
            "</string>\r\n  <string>제거식앵커공사-앵커1,2단 완료</string>\r\n  <string>제거식앵커공사-앵커3,4단 완료</st" +
            "ring>\r\n  <string>제거식앵커공사-앵커5,6,7단 완료</string>\r\n  <string>제거식앵커해체공사</string>\r\n  <" +
            "string>제연덕트 설치공사(수직)</string>\r\n  <string>제연덕트 설치공사(수평)</string>\r\n  <string>제연창조절" +
            "장치설치공사</string>\r\n  <string>제출 및 승인</string>\r\n  <string>제품보증서</string>\r\n  <string" +
            ">제품자료</string>\r\n  <string>조경공사</string>\r\n  <string>조경관수 및 배수공사</string>\r\n  <stri" +
            "ng>조경구조물공사-조경구조물공사(마감)</string>\r\n  <string>조경구조물공사-초기공사분(구조체)</string>\r\n  <strin" +
            "g>조경석공사</string>\r\n  <string>조경시설공사</string>\r\n  <string>조경시설물공사-안내시설 및 관리시설</stri" +
            "ng>\r\n  <string>조경시설물공사-휴게시설</string>\r\n  <string>조경토공사</string>\r\n  <string>조경포장공사" +
            "</string>\r\n  <string>조경포장공사-고무칩포장</string>\r\n  <string>조경포장공사-블럭포장</string>\r\n  <s" +
            "tring>조경포장공사-인조잔디/목재데크포장</string>\r\n  <string>조적공사</string>\r\n  <string>조적자재반입</st" +
            "ring>\r\n  <string>조합페인트공사</string>\r\n  <string>주민공동시설</string>\r\n  <string>주민카페 마감공" +
            "사</string>\r\n  <string>주방가구설치공사</string>\r\n  <string>주방벽타일공사</string>\r\n  <string>주" +
            "방상부장보온틀공사</string>\r\n  <string>주요자재반입</string>\r\n  <string>주자재비</string>\r\n  <strin" +
            "g>주자재비(급구간선공사)</string>\r\n  <string>주자재비(배수공사)-100%완료</string>\r\n  <string>주자재비(배수" +
            "공사)-중기55%완료</string>\r\n  <string>주자재비(배수공사)-중후기80%완료</string>\r\n  <string>주자재비(배수공" +
            "사)-초기30%완료</string>\r\n  <string>주자재비(오수공사)-100%완료</string>\r\n  <string>주자재비(오수공사)-" +
            "중기60%완료</string>\r\n  <string>주자재비(오수공사)-초기30%완료</string>\r\n  <string>주자재비(포장공사)-10" +
            "0%완료</string>\r\n  <string>주자재비(포장공사)-중기60%완료</string>\r\n  <string>주자재비(포장공사)-초기30%" +
            "완료</string>\r\n  <string>주자재비-네일1,2단 완료</string>\r\n  <string>주자재비-네일3,4단 완료</string" +
            ">\r\n  <string>주자재비-네일5,6단 완료</string>\r\n  <string>주자재비-앵커1,2단 완료</string>\r\n  <stri" +
            "ng>주자재비-앵커3,4단 완료</string>\r\n  <string>주자재비-앵커5,6,7단 완료</string>\r\n  <string>주차멈춤턱" +
            "설치공사</string>\r\n  <string>주차장 상부 방수공사</string>\r\n  <string>주차장 환기설비공사</string>\r\n  " +
            "<string>주차장교통표시공사</string>\r\n  <string>주차장램프바닥문양처리공사</string>\r\n  <string>준공검사 완료 " +
            "확인서</string>\r\n  <string>준공단계</string>\r\n  <string>준공도면</string>\r\n  <string>준공도서비<" +
            "/string>\r\n  <string>준공도서작성비</string>\r\n  <string>준공청소계획서</string>\r\n  <string>준공청소" +
            "비</string>\r\n  <string>줄눈설치공사</string>\r\n  <string>중앙감시실</string>\r\n  <string>중온수배관" +
            "공사</string>\r\n  <string>지급자재</string>\r\n  <string>지급자재 관리부</string>\r\n  <string>지급자" +
            "재 수급 요청서</string>\r\n  <string>지급자재 인계/인수서</string>\r\n  <string>지급자재반입</string>\r\n  " +
            "<string>지급자재현장관리비</string>\r\n  <string>지붕 및 홈통공사</string>\r\n  <string>지붕단열재설치공사</s" +
            "tring>\r\n  <string>지붕층</string>\r\n  <string>지붕콘크리트마감공사</string>\r\n  <string>지상10층</" +
            "string>\r\n  <string>지상10층-12층</string>\r\n  <string>지상11층</string>\r\n  <string>지상11층" +
            "-최상층</string>\r\n  <string>지상12층</string>\r\n  <string>지상13층</string>\r\n  <string>지상1" +
            "3층-15층</string>\r\n  <string>지상14층</string>\r\n  <string>지상15층</string>\r\n  <string>지" +
            "상16층</string>\r\n  <string>지상16층-18층</string>\r\n  <string>지상17층</string>\r\n  <string" +
            ">지상18층</string>\r\n  <string>지상1층</string>\r\n  <string>지상1층-3층</string>\r\n  <string>" +
            "지상2층</string>\r\n  <string>지상2층-10층</string>\r\n  <string>지상2층-최상층</string>\r\n  <stri" +
            "ng>지상2층10층</string>\r\n  <string>지상3층</string>\r\n  <string>지상4층</string>\r\n  <string" +
            ">지상4층-6층</string>\r\n  <string>지상5층</string>\r\n  <string>지상6층</string>\r\n  <string>지" +
            "상7층</string>\r\n  <string>지상7층-9층</string>\r\n  <string>지상8층</string>\r\n  <string>지상9" +
            "층</string>\r\n  <string>지장물 등 철거 작업계획서</string>\r\n  <string>지장물 이설신청</string>\r\n  <s" +
            "tring>지지물설치공사</string>\r\n  <string>지피 및 초화류 식재공사-100%완료</string>\r\n  <string>지피 및 " +
            "초화류 식재공사-초기50%완료</string>\r\n  <string>지피 및 초화류 지반조성공사</string>\r\n  <string>지하1층</s" +
            "tring>\r\n  <string>지하2층</string>\r\n  <string>지하3층</string>\r\n  <string>지하부속실</strin" +
            "g>\r\n  <string>지하수 개발신고</string>\r\n  <string>지하저수조</string>\r\n  <string>지하저수조전기공사</" +
            "string>\r\n  <string>지하주차장</string>\r\n  <string>지하주차장 에폭시 바닥마감공사</string>\r\n  <strin" +
            "g>지하주차장#501 </string>\r\n  <string>지하주차장#502</string>\r\n  <string>지하주차장#503A</strin" +
            "g>\r\n  <string>지하주차장#503B</string>\r\n  <string>지하주차장#504</string>\r\n  <string>지하주차장" +
            "#505</string>\r\n  <string>지하층</string>\r\n  <string>지하층마감</string>\r\n  <string>차량감속보" +
            "도</string>\r\n  <string>차량출입통제시스템 정보통신공사</string>\r\n  <string>차량통제시스템 전기공사</string>" +
            "\r\n  <string>착공간담회</string>\r\n  <string>착공단계</string>\r\n  <string>착공신고</string>\r\n  " +
            "<string>창틀주위모르타르충진공사</string>\r\n  <string>창호공사</string>\r\n  <string>창호설치형환기구설치공사</" +
            "string>\r\n  <string>천장 도배공사</string>\r\n  <string>천장틀설치공사</string>\r\n  <string>철근콘크리" +
            "트공사</string>\r\n  <string>철근콘크리트공사-구체100%완료</string>\r\n  <string>철근콘크리트공사-구체10m완료</" +
            "string>\r\n  <string>철근콘크리트공사-구체15m완료</string>\r\n  <string>철근콘크리트공사-구체20m완료</string" +
            ">\r\n  <string>철근콘크리트공사-구체22m완료</string>\r\n  <string>철근콘크리트공사-구체30m완료</string>\r\n  <" +
            "string>철근콘크리트자재 반입</string>\r\n  <string>철제커텐BOX설치공사</string>\r\n  <string>총괄시공확인계획서" +
            "</string>\r\n  <string>치환공사</string>\r\n  <string>침사지공사</string>\r\n  <string>칼라알루미늄 천" +
            "장판공사</string>\r\n  <string>칼라알루미늄스팬드럴공사</string>\r\n  <string>커텐박스설치공사</string>\r\n  <" +
            "string>커튼월설치공사</string>\r\n  <string>케이블공사</string>\r\n  <string>케이블트레이공사</string>\r\n" +
            "  <string>코아벽보온틀공사</string>\r\n  <string>콘크리트내벽면처리공사</string>\r\n  <string>콘크리트옹벽공사-" +
            "구체40m완료</string>\r\n  <string>콘크리트옹벽공사-구체80m완료</string>\r\n  <string>콘크리트옹벽공사-구체완료</" +
            "string>\r\n  <string>콘크리트옹벽공사-벽체마감완료</string>\r\n  <string>콘크리트외벽면처리공사</string>\r\n  <" +
            "string>콘크리트천장면처리공사</string>\r\n  <string>콘크리트타설시 부착 단열공사</string>\r\n  <string>콜크판설치" +
            "공사</string>\r\n  <string>콩자갈 수지포장</string>\r\n  <string>타워크레인공사</string>\r\n  <string>" +
            "타일공사</string>\r\n  <string>타일바탕벽모르터바르기공사</string>\r\n  <string>탄성퍼티공사</string>\r\n  <s" +
            "tring>태양광 발전 설치공사</string>\r\n  <string>테라조공사</string>\r\n  <string>테스트</string>\r\n  " +
            "<string>토공사</string>\r\n  <string>토공사(성토)-중기50%완료</string>\r\n  <string>토공사(성토)-초기30" +
            "%완료</string>\r\n  <string>토공사(외부반출토-사질토)-100%완료</string>\r\n  <string>토공사(외부반출토-사질토)" +
            "-중기50%완료</string>\r\n  <string>토공사(외부반출토-사질토)-중후기80%완료</string>\r\n  <string>토공사(외부반" +
            "출토-사질토)-초기30%완료</string>\r\n  <string>토공사(외부반출토-암반)-중기50%완료</string>\r\n  <string>토공" +
            "사(외부반출토-암반)-초기30%완료</string>\r\n  <string>토공사(절토-사질토)-100%완료</string>\r\n  <string>토" +
            "공사(절토-사질토)-중기50%완료</string>\r\n  <string>토공사(절토-사질토)-중후기80%완료</string>\r\n  <string>" +
            "토공사(절토-사질토)-초기30%완료</string>\r\n  <string>토공사(절토-암반)-100%완료</string>\r\n  <string>토공" +
            "사(절토-암반)-중기50%완료</string>\r\n  <string>토공사(절토-암반)-중후기80%완료</string>\r\n  <string>토공사" +
            "(절토-암반)-초기30%완료</string>\r\n  <string>토공사(현장내운반토)-중기50%완료</string>\r\n  <string>토공사(" +
            "현장내운반토)-초기30%완료</string>\r\n  <string>토목공사</string>\r\n  <string>토목시공상세도면</string>\r\n" +
            "  <string>통신공사</string>\r\n  <string>통합배관공사</string>\r\n  <string>통합배선설비공사</string>\r" +
            "\n  <string>트렌치설치공사</string>\r\n  <string>특고전력인입공사</string>\r\n  <string>파우더장설치공사</st" +
            "ring>\r\n  <string>판넬설치공사</string>\r\n  <string>판넬히팅공사</string>\r\n  <string>펌프실</stri" +
            "ng>\r\n  <string>펌프실 배관공사</string>\r\n  <string>펌프실배관공사</string>\r\n  <string>폐기물관리</s" +
            "tring>\r\n  <string>폐기물처리비</string>\r\n  <string>폐쇄회로텔레비전(CCTV)설비공사</string>\r\n  <str" +
            "ing>포리에칠렌필림 깔기</string>\r\n  <string>포장공사</string>\r\n  <string>포장공사(토공사))-100%완료</s" +
            "tring>\r\n  <string>포장공사(토공사))-중기60%완료</string>\r\n  <string>포장공사(토공사)-초기30%완료</stri" +
            "ng>\r\n  <string>포장공사섹터</string>\r\n  <string>폴리머모르터르바름공사</string>\r\n  <string>폴리머방수공" +
            "사</string>\r\n  <string>폼충진공사</string>\r\n  <string>표시판공사</string>\r\n  <string>품질 관리 " +
            "방안 Setting</string>\r\n  <string>품질관리</string>\r\n  <string>품질시험</string>\r\n  <string" +
            ">피뢰 및 접지공사</string>\r\n  <string>피뢰침설치공사</string>\r\n  <string>필로티</string>\r\n  <stri" +
            "ng>하도급 통보</string>\r\n  <string>하도자 신고 및 통보</string>\r\n  <string>함설치공사</string>\r\n  " +
            "<string>합성수지재창호설치공사</string>\r\n  <string>합성수지재창호틀설치공사</string>\r\n  <string>현관바닥타일공" +
            "사</string>\r\n  <string>현장보안공사</string>\r\n  <string>현장운영관련공사</string>\r\n  <string>현장" +
            "정리비</string>\r\n  <string>혼합골재포설공사-100%완료</string>\r\n  <string>혼합골재포설공사-중기60%완료</st" +
            "ring>\r\n  <string>혼합골재포설공사-초기30%완료</string>\r\n  <string>홈네트워크간선공사</string>\r\n  <str" +
            "ing>홈네트워크설비공사</string>\r\n  <string>홈네트워크시스템공사</string>\r\n  <string>홈통및 우수관 설치공사</s" +
            "tring>\r\n  <string>화강석판석포장공사</string>\r\n  <string>화장실바닥타일공사</string>\r\n  <string>화장" +
            "실벽타일공사</string>\r\n  <string>화장실칸막이공사</string>\r\n  <string>확인측량결과보고서</string>\r\n  <s" +
            "tring>확장형발코니샷시 난간설치공사</string>\r\n  <string>환경관련시설공사</string>\r\n  <string>환기설비공사</s" +
            "tring>\r\n  <string>휘트니스룸 마감공사</string>\r\n  <string>흙막이공사</string>\r\n  <string>흙막이벽체" +
            "설치공사-네일1,2단 완료</string>\r\n  <string>흙막이벽체설치공사-네일3,4단 완료</string>\r\n  <string>흙막이벽체" +
            "설치공사-네일5,6단 완료</string>\r\n  <string>흙막이벽체설치공사-앵커1,2단 완료</string>\r\n  <string>흙막이벽체" +
            "설치공사-앵커3,4단 완료</string>\r\n  <string>흙막이벽체설치공사-앵커5,6,7단 완료</string>\r\n  <string>흙막이" +
            "벽체해체공사</string>\r\n  <string>흡음판설치공사</string>\r\n  <string>？은유리공사</string>\r\n</ArrayO" +
            "fString>")]
        public global::System.Collections.Specialized.StringCollection register_type {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["register_type"]));
            }
            set {
                this["register_type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("register")]
        public string register_folder_uri {
            get {
                return ((string)(this["register_folder_uri"]));
            }
            set {
                this["register_folder_uri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("archive.db")]
        public string sqlite_db_location {
            get {
                return ((string)(this["sqlite_db_location"]));
            }
            set {
                this["sqlite_db_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SQLite")]
        public string db_type {
            get {
                return ((string)(this["db_type"]));
            }
            set {
                this["db_type"] = value;
            }
        }
    }
}
