//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pmis.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ko_KR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ko_KR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pmis.i18n.ko_KR", typeof(ko_KR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 의견.
        /// </summary>
        internal static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연제버전.
        /// </summary>
        internal static string current {
            get {
                return ResourceManager.GetString("current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string detail {
            get {
                return ResourceManager.GetString("detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 분야.
        /// </summary>
        internal static string discipline {
            get {
                return ResourceManager.GetString("discipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 문서분야.
        /// </summary>
        internal static string docdiscipline {
            get {
                return ResourceManager.GetString("docdiscipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 문서번호.
        /// </summary>
        internal static string docno {
            get {
                return ResourceManager.GetString("docno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 문서상태.
        /// </summary>
        internal static string docstatus {
            get {
                return ResourceManager.GetString("docstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 문서제목.
        /// </summary>
        internal static string doctitle {
            get {
                return ResourceManager.GetString("doctitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 문서구분.
        /// </summary>
        internal static string doctype {
            get {
                return ResourceManager.GetString("doctype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 파일 이름.
        /// </summary>
        internal static string file_name {
            get {
                return ResourceManager.GetString("file_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 일반.
        /// </summary>
        internal static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 일반 설정.
        /// </summary>
        internal static string general_settings {
            get {
                return ResourceManager.GetString("general_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이력.
        /// </summary>
        internal static string history {
            get {
                return ResourceManager.GetString("history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 내부번호.
        /// </summary>
        internal static string internalno {
            get {
                return ResourceManager.GetString("internalno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 수정날짜.
        /// </summary>
        internal static string modified {
            get {
                return ResourceManager.GetString("modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 메모.
        /// </summary>
        internal static string note {
            get {
                return ResourceManager.GetString("note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 번호.
        /// </summary>
        internal static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 조직.
        /// </summary>
        internal static string organization {
            get {
                return ResourceManager.GetString("organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록일자.
        /// </summary>
        internal static string registered {
            get {
                return ResourceManager.GetString("registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록자.
        /// </summary>
        internal static string registeredby {
            get {
                return ResourceManager.GetString("registeredby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 재설정 설정.
        /// </summary>
        internal static string reset_settings {
            get {
                return ResourceManager.GetString("reset_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 설정을 원래 기본값으로 복원한다..
        /// </summary>
        internal static string restore_settings_message {
            get {
                return ResourceManager.GetString("restore_settings_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 검토정보.
        /// </summary>
        internal static string review_info {
            get {
                return ResourceManager.GetString("review_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 검토결과.
        /// </summary>
        internal static string review_outcome {
            get {
                return ResourceManager.GetString("review_outcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Supplementary Files.
        /// </summary>
        internal static string review_supp_file {
            get {
                return ResourceManager.GetString("review_supp_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 검토의견.
        /// </summary>
        internal static string reviewdetail {
            get {
                return ResourceManager.GetString("reviewdetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 검토자.
        /// </summary>
        internal static string reviewed {
            get {
                return ResourceManager.GetString("reviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 검토일자.
        /// </summary>
        internal static string reviewed_by {
            get {
                return ResourceManager.GetString("reviewed_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 검토상태.
        /// </summary>
        internal static string reviewstatus {
            get {
                return ResourceManager.GetString("reviewstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision.
        /// </summary>
        internal static string revision {
            get {
                return ResourceManager.GetString("revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision Date.
        /// </summary>
        internal static string revisiondate {
            get {
                return ResourceManager.GetString("revisiondate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 검색.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 폴더에 표시.
        /// </summary>
        internal static string show_in_folder {
            get {
                return ResourceManager.GetString("show_in_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 크기.
        /// </summary>
        internal static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 상태.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 제목.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 구분.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 버전.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
    }
}
